import random
# ngram_list = ["1gram", "2gram", "3gram"]
# ngram_type = ""
# # while(ngram_type not in ngram_list):
# ngram_type = input("Please Enter engram type between 1gram-2gram-3gram:\n")
# seed = input("Now Enter seed number:\n")
n = input("How many sentences you like to be generated by this ngram?\n")

seed = 9


unigram_text = ''

txt_file = open("../../Model/pop/1gram.lm", 'r', encoding="utf-8")
for line in txt_file.readlines():
    line = line.rstrip()
    line += '|'
    unigram_text += line
unigram_list = unigram_text.split("|")
unigram_dict = {}
for i in range(0, len(unigram_list)-1, 2):
    unigram_dict[unigram_list[i]] = float(unigram_list[i+1])



txt_file = open("out.txt", 'w', encoding="utf-8")

for sentences in range(int(n)):
    counter = 0
    r_words_number = 1
    while(counter <= r_words_number):
        random_probability = random.random()
        temp = str(random_probability)
        r_words_number = int(temp[2])
        if r_words_number == 0:
            r_words_number = 6
        print(random_probability)
        sum = 0
        for i in unigram_dict:
            sum += unigram_dict[i]
            if sum > random_probability:
                print(unigram_dict[i])
                txt_file.write(i+" ")
                break
        counter += 1
    txt_file.write("\n")


